const questions = [
  {
    question: "imagenes/pregunta1.png",
    correctAnswer: "b",
    answers: ["a", "b", "c", "d"],
    classQuestions: "pregunta1",
    classPart: "parte1",
    errorPage: "imagenes/error1.png",
    errorStyle: "z-index:1; top: 29.3%; right: 5.1%",
  },
  {
    question: "imagenes/pregunta2.png",
    correctAnswer: "b",
    answers: ["a", "b", "c", "d"],
    classQuestions: "pregunta2",
    classPart: "parte2",
    errorPage: "imagenes/error2.png",
    errorStyle: "z-index:1; right: 5.1%; top: 29.3%;",
  },
  {
    question: "imagenes/pregunta3.png",
    correctAnswer: "a",
    answers: ["a", "b", "c", "d"],
    classQuestions: "pregunta3",
    classPart: "parte3",
    errorPage: "imagenes/error3.png",
    errorStyle: "z-index:1; right: 5.1%; top: 29.3%;",
  },
  {
    question: "imagenes/pregunta4.png",
    correctAnswer: "c",
    answers: ["a", "b", "c", "d"],
    classQuestions: "pregunta4",
    classPart: "parte4",
    errorPage: "imagenes/error4.png",
    errorStyle: "z-index:1; right: 5.1%; top: 29.3%;",
  },
  {
    question: "imagenes/pregunta5.png",
    correctAnswer: "b",
    answers: ["a", "b", "c", "d"],
    classQuestions: "pregunta5",
    classPart: "parte5",
    errorPage: "imagenes/error5.png",
    errorStyle: "z-index:1; right: 5.1%; top: 24.9%;",
  },
  {
    question: "imagenes/pregunta6.png",
    correctAnswer: "c",
    answers: ["a", "b", "c", "d"],
    classQuestions: "pregunta6",
    classPart: "parte6",
    errorPage: "imagenes/error6.png",
    errorStyle: "z-index:1; right: 5%; top: 25.7%;",
  },
  {
    question: "imagenes/pregunta7.png",
    correctAnswer: "d",
    answers: ["a", "b", "c", "d"],
    classQuestions: "pregunta7",
    classPart: "parte7",
    errorPage: "imagenes/error7.png",
    errorStyle: "z-index:1; right: 5%; top: 25.8%;",
  },
  {
    question: "imagenes/pregunta8.png",
    correctAnswer: "d",
    answers: ["a", "b", "c", "d"],
    classQuestions: "pregunta8",
    classPart: "parte8",
    errorPage: "imagenes/error8.png",
    errorStyle: "z-index:1; right: 5%; top: 25.8%;",
  },
  {
    question: "imagenes/pregunta9.png",
    correctAnswer: "a",
    answers: ["a", "b"],
    classQuestions: "pregunta9",
    positiona: "53.3%",
    positionb: "79.8%",
    classPart: "parte9",
  },
  {
    question: "imagenes/pregunta10.png",
    correctAnswer: "a",
    answers: ["a", "b"],
    classQuestions: "pregunta10",
    positiona: "53.3%",
    positionb: "79.8%",
    classPart: "parte10",
  },
  {
    question: "imagenes/pregunta11.png",
    correctAnswer: "a",
    answers: ["a", "b"],
    classQuestions: "pregunta11",
    positiona: "53.3%",
    positionb: "79.8%",
    classPart: "parte11",
  },
  {
    question: "imagenes/pregunta12.png",
    correctAnswer: "b",
    answers: ["a", "b"],
    classQuestions: "pregunta12",
    positiona: "53.3%",
    positionb: "79.8%",
    classPart: "parte12",
  },
  {
    question: "imagenes/pregunta13.png",
    correctAnswer: "b",
    answers: ["a", "b"],
    classQuestions: "pregunta13",
    positiona: "53.3%",
    positionb: "79.8%",
    classPart: "parte13",
  },
];
